"""initial schema

Revision ID: b1fd1e47ebc2
Revises:
Create Date: 2026-09-09 21:48:51.511189
"""

from collections.abc import Sequence

import geoalchemy2
import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b1fd1e47ebc2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # infra/postgres/init.sql does this for the local container; a managed host
    # (Render) hands over an empty database, so the migration must be self-sufficient.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("change_id", sa.UUID(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("git_sha", sa.String(length=40), nullable=True),
        sa.Column("model_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prompt_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "buildings",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column(
            "footprint",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                srid=32643,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("zone", sa.Enum("core", "buffer", "outside", name="zone"), nullable=False),
        sa.Column("chowkri_id", sa.String(length=32), nullable=True),
        sa.Column("source_ref", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clauses",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("regulation", sa.String(length=256), nullable=False),
        sa.Column("section", sa.String(length=32), nullable=False),
        sa.Column("clause", sa.String(length=32), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("applies_to_zone", postgresql.ARRAY(sa.String(length=16)), nullable=False),
        sa.Column("applies_to_change_type", postgresql.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("source_page", sa.Integer(), nullable=False),
        sa.Column("source_doc_sha256", sa.String(length=64), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "officers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("role", sa.Enum("officer", "reviewer", "admin", name="role"), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("epoch_before", sa.Date(), nullable=False),
        sa.Column("epoch_after", sa.Date(), nullable=False),
        sa.Column("git_sha", sa.String(length=40), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("progress", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tiles",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                srid=32643,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("centroid_lon", sa.Float(), nullable=False),
        sa.Column("centroid_lat", sa.Float(), nullable=False),
        sa.Column("zone", sa.Enum("core", "buffer", "outside", name="zone"), nullable=False),
        sa.Column("chowkri_id", sa.String(length=32), nullable=True),
        sa.Column("quarantined", sa.Boolean(), nullable=False),
        sa.Column("residual_px", sa.Float(), nullable=True),
        sa.Column("season_mismatch", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "changes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("tile_id", sa.String(length=64), nullable=False),
        sa.Column("building_id", sa.String(length=16), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=32643,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("zone", sa.Enum("core", "buffer", "outside", name="zone"), nullable=False),
        sa.Column("chowkri_id", sa.String(length=32), nullable=True),
        sa.Column("epoch_before", sa.Date(), nullable=False),
        sa.Column("epoch_after", sa.Date(), nullable=False),
        sa.Column("change_prob", sa.Float(), nullable=False),
        sa.Column("calibration_date", sa.Date(), nullable=True),
        sa.Column(
            "change_type",
            sa.Enum(
                "NEW_CONSTRUCTION",
                "VERTICAL_ADDITION",
                "DEMOLITION",
                "FACADE_ALTERATION",
                name="change_type",
            ),
            nullable=False,
        ),
        sa.Column("facade_class", sa.String(length=32), nullable=True),
        sa.Column("before_uri", sa.String(length=512), nullable=False),
        sa.Column("after_uri", sa.String(length=512), nullable=False),
        sa.Column("mask_uri", sa.String(length=512), nullable=False),
        sa.Column("triage_decision", sa.String(length=32), nullable=True),
        sa.Column("triage_reason", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                "escalated",
                "dropped",
                "needs_human_rewrite",
                name="change_status",
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("verifier_verdict", sa.String(length=8), nullable=True),
        sa.Column("verifier_notes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("revision_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["buildings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tile_id"],
            ["tiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("change_id", sa.UUID(), nullable=False),
        sa.Column("officer_id", sa.UUID(), nullable=False),
        sa.Column(
            "decision", sa.Enum("approve", "reject", "escalate", name="decision"), nullable=False
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["change_id"],
            ["changes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["officer_id"],
            ["officers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "findings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("change_id", sa.UUID(), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("clause_id", sa.String(length=64), nullable=False),
        sa.Column("evidence_ref", sa.String(length=512), nullable=False),
        sa.Column("severity", sa.Enum("low", "medium", "high", name="severity"), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("is_final", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["change_id"],
            ["changes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["clause_id"],
            ["clauses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("officer_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("change_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["change_id"],
            ["changes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["officer_id"],
            ["officers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "site_visits",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("change_id", sa.UUID(), nullable=False),
        sa.Column("scheduled_for", sa.Date(), nullable=False),
        sa.Column("assignee_id", sa.UUID(), nullable=True),
        sa.Column(
            "status", sa.Enum("scheduled", "done", "cancelled", name="visit_status"), nullable=False
        ),
        sa.Column("field_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["officers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["change_id"],
            ["changes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        """
        CREATE FUNCTION audit_log_immutable() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log is append-only';
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER audit_log_no_update_delete
            BEFORE UPDATE OR DELETE ON audit_log
            FOR EACH ROW EXECUTE FUNCTION audit_log_immutable();
        CREATE TRIGGER audit_log_no_truncate
            BEFORE TRUNCATE ON audit_log
            FOR EACH STATEMENT EXECUTE FUNCTION audit_log_immutable();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_truncate ON audit_log")
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_update_delete ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS audit_log_immutable")
    op.drop_table("site_visits")
    op.drop_table("notifications")
    op.drop_table("findings")
    op.drop_table("decisions")
    op.drop_table("changes")
    op.drop_table("tiles")
    op.drop_table("runs")
    op.drop_table("officers")
    op.drop_table("clauses")
    op.drop_table("buildings")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS change_status")
    op.execute("DROP TYPE IF EXISTS change_type")
    op.execute("DROP TYPE IF EXISTS decision")
    op.execute("DROP TYPE IF EXISTS role")
    op.execute("DROP TYPE IF EXISTS severity")
    op.execute("DROP TYPE IF EXISTS visit_status")
    op.execute("DROP TYPE IF EXISTS zone")
